trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  version.MajorMinor: '1.0' 
  version.Revision: $[counter(variables['version.MajorMinor'], 0)]
  versionNumber: '$(version.MajorMinor).$(version.Revision)'

resources:
  repositories:
  - repository: C4E_SFDC_Templates
    type: git
    name: C4E_SFDC_Templates/C4E_SFDC_Templates

  
stages:
  - template: Mulesoft-cicd-templates/mulesoft-cicd-maven-template.yml@C4E_SFDC_Templates
    parameters:
      disableCheckmarx: True
      appname_override: True
      mulesoft_app_name: traksys-erp-integration-c4e-cicd-app
      mulesoft_app_override_name: $(project.name)
      environment: sit
      sonarqube_service_name: ABI_SonarQube
      sonarqube_project_name: Tech_Supply_Mes_MuleSoft
      sonarqube_project_key: Tech_Supply_Mes_MuleSoft
      artifactory_service_name: ABI_Artifactory
      artifactory_repository_name: Tech_Supply_Mes_MuleSoft
      mulesoft_abi_orgid: "475738d6-fd5d-4dce-8860-7eb1deb80103"
      mulesoft_onprem_deployment: True
      mulesoft_onprem_server_name: $(project.target)
      Anypoint_sandbox_name: $(project.environment)